import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css';
import ScrollToTopButton from "@/components/ScrollToTopButton/ScrollToTopButton";

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-kanit",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});

// font-thin = 100;
// font-extralight = 200;
// font-light = 300;
// font-normal = 400;
// font-medium = 500;
// font-semibold = 600;
// font-bold = 700;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable} antialiased`}
      >
        {children}
        <ScrollToTopButton />
      </body>
    </html>
  );
}
